### ISSUE TITLE
PublishedApplications: Content from referenced assemblies copied to incorrect output directory

### ISSUE THREAD

**Issue by jrnail23** [ferventcoder/nugetpackages#121]
Content marked "Copy to Output Directory" contained in a folder (LibraryB/MyContent/MyFile.txt) in a referenced assembly will be copied to the root folder of the targeted PublishedApplication (i.e., _PublishedApplications/MyApp/MyFile.txt) instead of the containing folder (PublishedApplications/MyApp/MyContent/MyFile.txt)

Please see https://github.com/jrnail23/PublishedApplications.Example for a simple example of this behavior

**Comment by ferventcoder** [comment]
Fixed by #138.
