### ISSUE TITLE
Install Ruby from ZIP, not from Windows Installer.

### ISSUE THREAD

**Issue by kostrse** [ferventcoder/nugetpackages#136]
Chocolatey doesn't follow a standard way of installing applications in Windows.

I believe, there's no point of executing MSI to trash up Windows registry , and point the installer to a custom location.

It could be more clean to just download/unpack zip to a Chocolatey folder and set all necessary Path and RUBY_HOME variables.

**Comment by ferventcoder** [comment]
Closing as a ruby.portable package now exists.
